# Generated by Django 4.2.1 on 2023-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nr_of_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
